---
- name: Upgrade all packages
  yum: name=* state=latest

- name: Install wget
  yum: name=wget state=present

- name: Install curl
  yum: name=curl state=present

- name: Install Networking tools
  yum: name=net-tools state=present

- name: Install NTP
  yum: name=ntp state=present

- name: Install vim
  yum: name=vim state=present

- name: Install nano
  yum: name=nano state=present

- name: Install policy utilities
  yum: policycoreutils-python state=present

- name: Install yum-cron for automatic security updates
  yum: name=yum-cron state=present
  notify: restart yum-cron

- name: Copy yum-cron configuration for automatic security updates
  copy: src=yum-cron.conf dest=/etc/yum/yum-cron.conf
  notify: restart yum-cron

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Copying SELinux configuration
  copy: src=selinux dest=/etc/sysconfig/selinux

- name: Install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: Add deploy user
  action: user name=deploy password={{ deploy_passwd }}

- name: Add authorized deploy key for deploy user
  action: authorized_key user=deploy key="{{ item }}"
  with_file:
    - public_keys/ked.pub

- name: Remove sudo group rights
  action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Add deploy user to sudoers
  lineinfile: dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) ALL" state=present

- name: Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: restart sshd

- name: Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart sshd
