---
- name: Install Java Runtime
  yum: name=java-1.7.0-openjdk.x86_64 state=present

- name: Install Java JDK
  yum: name=java-1.7.0-openjdk-devel.x86_64 state=present

- name: Add Logstash repo key
  rpm_key: key="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Enable Elasticsearch repository
  template: src=elasticsearch_repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install Elasticsearch from repository
  yum: name=elasticsearch state=present

- name: Elasticsearch configuration
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify: restart elasticsearch
  tags: configuration

- name: Allow incoming TCP connections (9200-9400)
  firewalld: port=9200-9400/tcp permanent=true state=enabled
  notify: restart firewalld
  tags: configuration
