---
- hosts: node-servers
  remote_user: deploy
  serial: 1 # only one machine at the time

  vars:
    git_repo: "https://github.com/ToastShaman/zuhlke-2014-camp-talk.git"
    project_src: "./backend"

  vars_prompt:
    - name: "backend_version"
      prompt: "What version should be deployed? (default=HEAD)"
      default: "HEAD"

  tasks:
  - name: Pull sources from the repository
    git: repo={{ git_repo }} dest={{ project_src }}-{{ backend_version }} version={{ backend_version }}

  - name: Create a symlink to the current version
    file: src={{ project_src }}-{{ backend_version }}/server dest=backend-current state=link

  - name: NPM install the dependencies
    npm: path=/home/deploy/backend-current

  - name: Make the scripts executable
    file: path=/home/deploy/backend-current/bin/{{ item }} state=file mode="744"
    with_items: 
      - start_with_cluster
      - start_with_pm2

  - name: Copy the configuration settings
    template: src=deploy/templates/configuration.json.j2 dest=/home/deploy/backend-current/bin/configuration.json

  - name: Allow incoming HTTP connections
    sudo: true
    firewalld: port=8080/tcp permanent=true state=enabled
    notify: restart firewalld

  - name: Stop the backend
    shell: pm2 stop all

  - name: Start the backend
    shell: pm2 start /home/deploy/backend-current/bin/start_with_pm2

  - name: Save the pm2 process list
    shell: pm2 save

  - name: Generate pm2 startup scripts
    shell: pm2 startup -u deploy systemd

  #handlers:
  #  - include: deploy/handlers/main.yml

#- hosts: web-servers
#  remote_user: zuhlke
#  sudo: true
#  serial: 1

#  - name: Restart nginx
#    service: name=nginx state=restarted
