---
- name: Copy the mongodb repository definition
  copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo

- name: Install MongoDb
  yum: name=mongodb-org state=latest

- name: Configure mongodb 
  copy: src=mongod.conf dest=/etc/mongod.conf
  notify: restart mongodb

- name: Allow incoming mongodb connections
  firewalld: port=27017/tcp permanent=true state=enabled
  notify: restart firewalld
