---
- name: Copy the mongodb repository definition
  copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo

- name: Install mongodb tools
  yum: name=mongo-10gen state=latest

- name: Create mongodb PID file
  shell: install -d -m 0755 -o mongod -g mongod /var/run/mongodb/

- name: Configure mongodb 
  copy: src=mongod.conf dest=/etc/mongod.conf
  notify: restart mongodb
  tags: configuration

- name: Allow incoming mongodb connections
  firewalld: port=27017/tcp permanent=true state=enabled
  notify: restart firewalld
  tags: configuration
