---
- name: restart iptables
  service: name=iptables state=restarted

- name: restart sshd
  service: name=sshd state=restarted

- name: restart yum-cron
  service: name=yum-cron state=restarted enabled=yes

- name: restart ntp
  service: name=ntp state=restarted
