---
- name: Install nginx
  yum: name=nginx state=present

- name: Install nginx-extras
  yum: name=nginx-extras state=present

- name: Copy nginx SSL keys
  copy: src=ssl dest=/etc/nginx/

- name: Copy nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Allow incoming HTTP connections
  firewalld: service=http permanent=true state=enabled

- name: Allow incoming HTTPS connections
  firewalld: service=https permanent=true state=enabled
  notify: restart firewalld
