---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx SSL keys
  copy: src=ssl dest=/etc/nginx/
  tags: configuration

- name: Copy nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx
  tags: configuration

- name: Allow incoming HTTP connections
  firewalld: service=http permanent=true state=enabled
  tags: configuration

- name: Allow incoming HTTPS connections
  firewalld: service=https permanent=true state=enabled
  notify: restart firewalld
  tags: configuration
