---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx SSL keys
  copy: src=ssl dest=/etc/nginx/

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
